# Generated by Django 6.0 on 2025-12-11 17:05

from datetime import date, timedelta

from django.db import migrations


def get_sunday_of_week(d: date) -> date:
    days_until_sunday = 6 - d.weekday()
    return d + timedelta(days=days_until_sunday)


def get_end_of_month(d: date) -> date:
    if d.month == 12:
        return d.replace(day=31)
    return d.replace(month=d.month + 1, day=1) - timedelta(days=1)


def migrate_time_horizon_to_due_date(apps, schema_editor):
    """Convert time_horizon values to due_dates for tasks without a due_date."""
    Task = apps.get_model("core", "Task")
    today = date.today()

    for task in Task.objects.filter(due_date__isnull=True):
        if task.time_horizon == "today":
            task.due_date = today
        elif task.time_horizon == "this_week":
            task.due_date = get_sunday_of_week(today)
        elif task.time_horizon == "next_week":
            task.due_date = get_sunday_of_week(today) + timedelta(days=7)
        elif task.time_horizon == "later":
            task.due_date = get_end_of_month(today)
        # backlog tasks stay with due_date=None
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_time_horizon_to_due_date, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="task",
            name="time_horizon",
        ),
    ]
