# Generated by Django 6.0 on 2025-12-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_time_horizon_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="has_seen_tour",
            field=models.BooleanField(default=False),
        ),
    ]
