# Generated by Django 6.0 on 2025-12-12 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_has_seen_tour"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_id", models.CharField(max_length=200)),
                ("calendar_name", models.CharField(blank=True, max_length=200)),
                ("calendar_color", models.CharField(blank=True, max_length=20)),
                ("sync_token", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="etag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="location",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="status",
            field=models.CharField(default="confirmed", max_length=20),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["user", "start", "end"], name="core_calend_user_id_4a9b6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["user", "calendar_id"], name="core_calend_user_id_9c5988_idx"
            ),
        ),
        migrations.AddField(
            model_name="calendarsyncstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_sync_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calendarsyncstate",
            unique_together={("user", "calendar_id")},
        ),
    ]
