# Generated by Django 6.0 on 2025-12-12 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_calendar_sync_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="calendarevent",
            unique_together={("user", "calendar_id", "gcal_id")},
        ),
    ]
