# Generated by Django 6.0 on 2025-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="week_starts_on",
            field=models.IntegerField(
                choices=[
                    (0, "Sunday"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                ],
                default=1,
            ),
        ),
    ]
