# Generated by Django 6.0 on 2025-12-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_week_starts_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
