# Generated by Django 6.0 on 2025-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reschedule_count",
            field=models.IntegerField(default=0),
        ),
    ]
