# Generated by Django 6.0 on 2025-12-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_task_reschedule_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="scheduling_windows",
            field=models.JSONField(default=dict),
        ),
    ]
